;Exercise 1.15.  The sine of an angle (specified in radians) can be computed by making use of the approximation ... if x is sufficiently
;small, and the trigonometric identity ...

;to reduce the size of the argument of sin. (For purposes of this exercise an angle is considered ``sufficiently small'' if its magnitude is
;not greater than 0.1 radians.) These ideas are incorporated in the following procedures:

(define (cube x) (* x x x))

(define (p x) (- (* 3 x) (* 4 (cube x))))

(define (sine angle)
     (if (not (> (abs angle) 0.1))
         angle
         (p (sine (/ angle 3.0)))) )


;a.  How many times is the procedure p applied when (sine 12.15) is evaluated?

;b.  What is the order of growth in space and number of steps (as a function of a) used by the process generated by the sine procedure when
;(sine a) is evaluated? 


; 1 (sine 12.15)
; 2 (sine 4.05)
; 3 (sine 1.35)
; 4 (sine 0.45)
; 5 (sine 0.15)
; 6 (sine 0.05)
;6 times

;Time complexity 
;O(n)=log(n)

;Space complexity
;O(n)=log(n)
